hexapod :
	#Publish all joint states -----------
	joint_state_controller:
		type: joint_state_controller/JointStateController
		publish_rate: 50

	#Postion controlllers ---------------

	#Coxa joints
	coxa_l1_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_coxa_l1
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    coxa_l2_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_coxa_l2
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    coxa_l3_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_coxa_l3
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    coxa_r1_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_coxa_r1
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    coxa_r2_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_coxa_r2
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    coxa_r3_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_coxa_r3
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    #Femur joints
    femur_l1_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_femur_l1
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    femur_l2_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_femur_l2
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    femur_l3_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_femur_l3
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    femur_r1_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_femur_r1
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    femur_r2_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_femur_r2
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    femur_r3_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_femur_r3
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    #Tibia joints 
    tibia_l1_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_tibia_l1
    	pid: {p: 100.0, i: 0.01, d: 10.0}

   tibia_l2_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_tibia_l2
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    tibia_l3_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_tibia_l3
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    tibia_r1_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_tibia_r1
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    tibia_r2_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_tibia_r2
    	pid: {p: 100.0, i: 0.01, d: 10.0}

    tibia_r3_joint_position_controller:
    	type: effort_controllers/JointPositionController
    	joint: joint_tibia_r3
    	pid: {p: 100.0, i: 0.01, d: 10.0}
